name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read
  attestations: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests with coverage report output
        run: go test -v ./... -coverprofile=coverage.out
      - name: Run k1LoW/octocov
        uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
