name: gocredits
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  gocredits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      id: setup-go
      with:
        go-version-file: go.mod
    - name: Install dependencies
      run: go mod tidy
    - uses: yasu89/gocredits-action@de0d1b0dbcf41cbb27ef205029e65454045790ee # v1.0.0
